### ISSUE TITLE
要求は中止されました: SSL/TLS のセキュリティで保護されているチャネルを作成できませんでした

### ISSUE THREAD

**Issue by Blocker0043** [builtbyvichingo455/Notepad#2]
***Notepad version 1.1.3.0***

**Message**
要求は中止されました: SSL/TLS のセキュリティで保護されているチャネルを作成できませんでした

**Source**
System

**Stack Trace**
```   場所 System.Net.HttpWebRequest.GetResponse()
   場所 Notepad.Form1.CheckUpdates()```

**Comment by Vichingo455** [comment]
Duplicate of #1
